# Пользователи
## Регистрация пользователя

POST http://localhost:8085/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "test-user3@test.net",
  "avatar": "test.png",
  "name": "TestName",
  "password": "12345678",
  "type": "pro"
}

###

## Авторизация пользователя

POST http://localhost:8085/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "test-user3@test.net",
  "password": "12345678"
}

###

## Проверить токен пользователя

GET http://localhost:8085/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3QtdXNlckB0ZXN0Lm5ldCIsImlkIjoiNjQ5YzA4N2Y1MjVkODc4Nzc4ZTk4YTQ3IiwiaWF0IjoxNjg3OTQ3Mzk2LCJleHAiOjE2ODgxMjAxOTZ9.YyUAquxgN-ggYJ9-Aks8DhIc8m4GeMzldXc9MuBW_gA

###

## Отправить изображение

POST http://localhost:8085/users/649c1040add2176b5d1572ad/avatar HTTP/1.1
Content-Type: multipart/form-data;

Content-Disposition: form-data; name="avatar"; filename="pizzly.jpg"
Content-Type: image/jpg

< /Users/tmp/pizzly.jpg

###
