# Пользователи
## Регистрация пользователя

POST http://localhost:8085/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "test-user@test.net",
  "avatar": "test.png",
  "name": "TestName",
  "password": "12345678",
  "isPro": true
}

###

## Авторизация пользователя

POST http://localhost:8085/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "test-user@test.net",
  "password": "12345678"
}

###

## Проверить токен пользователя

GET http://localhost:8085/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3QtdXNlckB0ZXN0Lm5ldCIsImlkIjoiNjQ5MDhjNDIxZTZlNzdmNzRmYWZjZWU3IiwiaWF0IjoxNjg3NzA1MzYzLCJleHAiOjE2ODc4NzgxNjN9.zCMKW4y8qDMEOirKHnRgCY7S_9b09OD6Uv7rr9TPfcg

###
